Extract main trace building
lambdaclass/lambdaworks_cairo_prover pull request #59
Opened 2023-06-12 15:48 UTC by gabrielbosio

2023-06-12 19:18 UTC, entropidelic commented on src/cairo_run/run.rs
> +    let cairo_trace = RegisterStates::from_bytes_le(&trace_vec).unwrap();
`register_states`

2023-06-12 19:19 UTC, entropidelic commented on src/cairo_run/run.rs
> +        let raw_trace = RegisterStates::from_file(&dir_trace).unwrap();
register_states

2023-06-12 19:22 UTC, entropidelic requested changes

2023-06-12 19:22 UTC, entropidelic commented on src/cairo_vm/cairo_trace.rs
> +        let trace = RegisterStates::from_file(&dir).unwrap();
register_states

2023-06-12 19:22 UTC, entropidelic commented on src/cairo_vm/cairo_trace.rs
> +        let expected_trace = RegisterStates {
expected_reg_states

2023-06-12 19:22 UTC, entropidelic commented on src/cairo_vm/execution_trace.rs
> +    raw_trace: &RegisterStates,
register_states

2023-06-12 19:22 UTC, entropidelic commented on src/cairo_vm/execution_trace.rs
> +    raw_trace: &RegisterStates,
register_states

2023-06-12 19:22 UTC, entropidelic commented on src/cairo_vm/execution_trace.rs
> +    raw_trace: &RegisterStates,
register_states

2023-06-12 19:22 UTC, entropidelic commented on src/cairo_vm/execution_trace.rs
> +    raw_trace: &RegisterStates,
register_states

2023-06-12 19:22 UTC, entropidelic commented on src/cairo_vm/execution_trace.rs
> +        let raw_trace = RegisterStates::from_file(&dir_trace).unwrap();
register_states

2023-06-12 19:22 UTC, entropidelic commented on src/cairo_vm/execution_trace.rs
> +        let raw_trace = RegisterStates::from_file(&dir_trace).unwrap();
register_states

2023-06-12 19:39 UTC, entropidelic approved these changes

2023-06-13 17:25 UTC, diegokingston approved these changes

2023-06-13 17:49 UTC, merged